#ALGORITMO
#PEDIR EL VALOR DE LA BASE DEL TRIANGULO
#PEDIR EL VALOR DE LA ALTURA DEL TRIANGULO
#CALCULAR EL AREA AREA=(BASE*ALTURA)*2
#MOSTRAR EL AREA 
#COMPARAR RESULTADO CON NUMERO 100
#EL AREA ES MAYOR QUE 100 MUESTRA TRUE
#EL AREA ES MENOR O IGUAL A 100 MUESTRA FALSE

#PSEUDOCODIGO
#INICIO
#LEER LA BASE DEL TRIANGULO
#LEER LA ALTURA DEL TRIANGULO
#AREA (BASE*ALTURA)/2
#ESCRIBIR SI EL AREA 
#ESCRIBIR ES MAYOR QUE 100
#ESCRIBIR SI EL AREA ES MENOR O IGUAL A 100

base=float(input("Ingrese el valor de la base: "))
altura=float(input("Ingrese el valor de la altura: "))
area=(base*altura)/2
print("El area del triangulo es mayor que 100", area>100)
